name: high-refine-pifu
ckpt_dir: "./data/ckpt/"
resume_path: "./data/ckpt/refine-pifu/epoch=09.ckpt"
high_resume_path: "./data/ckpt/high-refine-pifu/epoch=06.ckpt"
normal_path: "./data/ckpt/normal.ckpt"

test_mode: True
batch_size: 1

net:
  mlp_dim: [256, 512, 256, 128, 1]
  res_layers: [2,3,4]
  num_stack: 2
  prior_type: "refinepifu" # icon/pamir/icon
  use_filter: True
  in_geo: (('image',3), ('normal_F',3), ('normal_B',3))
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))
  smpl_feats: ['sdf']
  gtype: 'HGPIFuNet'
  norm_mlp: 'batch'
  hourglass_dim: 6
  voxel_dim: 7
  smpl_dim: 1
  high_res_voxel: True
  use_normals: True
  

# user defined
mcube_res: 512    # occupancy field resolution, higher --> more details
clean_mesh: False # if True, will remove floating pieces